export const data = [
  {
    key: "111",
    title: "Need Landscaping Services? Free estimates!",
    brand: "Tobin’s Landscaping",
    area: "Upper St. Clair, PA",
    designation: "Asian",
  },
  {
    key: "112",
    title: "Retaining Walls, French Drains, and Hardscaping",
    brand: "Creekside Landscape Supply",
    area: "Pittsburgh, PA",
    designation: "black",
  },
  {
    key: "113",
    title: "TOBIN’S LANDSCAPING - WE SHOW UP!",
    brand: "Tobin’s Landscaping",
    area: "Upper St. Clair, PA",
    designation: "Hispanic",
  },
  {
    key: "114",
    title: "Bartlett Tree Experts - Free Estimates",
    brand: "Bartlett Tree Experts",
    area: "Mt. Lebanon, PAA",
    designation: "black",
  },
  {
    key: "115",
    title: "Scenic View Lawn Care: Residential / Commercial",
    brand: "Scenic View Lawn Care and Landscaping",
    area: "Upper St. Clair, PA",
    designation: "Asian",
  },
  {
    key: "116",
    title: "Need Landscaping Services? Free estimates!",
    brand: "Leisure Time Landscaping",
    area: "Upper St. Clair, PA",
    designation: "Veteran",
  },
  {
    key: "117",
    title: "Upgrade your property with JPS Landscape Construction",
    brand: "JPS Landscape Construction",
    area: "Upper St. Clair, PA",
    designation: "Asian",
  },
  {
    key: "118",
    title: "All year round seasonal care for your lawn and garden",
    brand: "4 Seasons Lawn & Garden Inc",
    area: "Upper St. Clair, PA",
    designation: "Asian",
  },
  {
    key: "119",
    title: "Need Landscaping Services? Free estimates!",
    brand: "Tobin’s Landscaping",
    area: "Upper St. Clair, PA",
    designation: "Asian",
  },
  {
    key: "110",
    title: "Need Landscaping Services? Free estimates!",
    brand: "Tobin’s Landscaping",
    area: "Upper St. Clair, PA",
    designation: "black",
  },
];
